### ISSUE TITLE
微信退款失败

### ISSUE THREAD

**Issue by cxyangs** [easy-swoole/pay#11]
目前在swoole3.3.1使用微信退款接口成功；
但是在swoole3.3.3退款失败，通过打印http请求错误信息：Connection reset by peer，http错误吗104 
异常提示地址throw new GatewayException('Get Wechat API Error url:' . $this->config->getGateWay() . $endpoint . ' params:' . $bean->__toString(), 20000) in vendor/easyswoole/pay/src/WeChat/Utility.php 104

**Comment by xiaocaigua** [comment]
swoole只发了3.0 的alpha，麻烦确认下你的swoole版本和easyswoole的版本

**Comment by cxyangs** [comment]
swoole4.3.3
easyswoole3.2.2-dev
抱歉，版本号写错了
正常运行环境swoole4.3.1,easyswoole版本一样

**Comment by xiaocaigua** [comment]
这个是swoole 4.3.3底层的修改了。。。可以拉取swoole的master的分支

**Comment by xiaocaigua** [comment]
4.3.3的bug，请安装最新swoole master版本

**Comment by cxyangs** [comment]
好的，谢谢
