### ISSUE TITLE
支付宝，统一收单下单并支付页面接口

### ISSUE THREAD

**Issue by lizz89** [easy-swoole/pay#24]
错误代码 invalid-signature 错误原因: 验签出错，请确认charset参数放在了URL查询字符串中且各参数值使用charset参数指示的字符集编码

**Comment by kiss291323003** [comment]
你依赖一下dev包，就没问题了

**Comment by hackjun** [comment]
大佬 “你依赖一下dev包，就没问题了”  是什么意思

**Comment by wenxin2008007** [comment]
> 错误代码 invalid-signature 错误原因: 验签出错，请确认charset参数放在了URL查询字符串中且各参数值使用charset参数指示的字符集编码

请问问题解决了么？如何解决的？
