### ISSUE TITLE
微信支付 HMAC-SHA256 加密方式提示 sign is error

### ISSUE THREAD

**Issue by alanchen365** [easy-swoole/pay#38]
![image](https://user-images.githubusercontent.com/22911460/99868854-4b02db80-2c01-11eb-90f6-b81a29361c0e.png)
![image](https://user-images.githubusercontent.com/22911460/99868872-75ed2f80-2c01-11eb-8ae9-31d7ed026193.png)

原因在于 如果使用的是HMAC-SHA256加密方式，在请求微信回来后，并没有携带签名类型sign_type的字段，程序判断时，认为没有这个字段的话， 就是MD5的签名方式， 所以用MD5方式的签名方式和HMAC-SHA256对比，报错。。。

![image](https://user-images.githubusercontent.com/22911460/99868936-09266500-2c02-11eb-814c-d65e056dec5e.png)

**Comment by XueSiLf** [comment]
马上修正
