### ISSUE TITLE
支付宝转账老接口已废弃，建议升级到新接口 alipay.fund.trans.uni.transfer

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/pay#48]
https://github.com/easy-swoole/pay/blob/1ca1af8466aaba8ca0e6b1afa7b7c3da506c8aa7/src/AliPay/RequestBean/Transfer.php#L14

https://opendocs.alipay.com/apis/api_28/alipay.fund.trans.uni.transfer/

**Comment by Stitch-June** [comment]
@XueSiLf

**Comment by XueSiLf** [comment]
该接口已经升级，且已发布新版本。
